services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-frontend

  todo-frontend:
    image: todo-frontend-dev
    build:
      context: ./todo-app/todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-app/todo-frontend:/usr/src/app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]